GRANT USAGE ON SCHEMA ai_router TO proxyrouter_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA ai_router TO proxyrouter_user;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA ai_router TO proxyrouter_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA ai_router GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO proxyrouter_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA ai_router GRANT USAGE, SELECT ON SEQUENCES TO proxyrouter_user;
